# Generated by Django 3.1.1 on 2020-09-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='subtitle',
            field=models.CharField(blank=True, max_length=150, verbose_name='Подзаголовок'),
        ),
    ]
