# Generated by Django 3.1.1 on 2020-09-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='img',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='services',
            name='subtitle',
            field=models.CharField(blank=True, max_length=150, verbose_name='Подзаголовок'),
        ),
    ]
