# Generated by Django 3.1.1 on 2020-10-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSeo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name='title')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='description')),
                ('og_title', models.CharField(blank=True, max_length=250, verbose_name='og:title')),
                ('og_description', models.CharField(blank=True, max_length=250, verbose_name='og:description')),
                ('og_url', models.CharField(blank=True, max_length=250, verbose_name='og:url')),
                ('og_image', models.CharField(blank=True, max_length=250, verbose_name='og:image')),
                ('og_type', models.CharField(blank=True, default='website', max_length=250, verbose_name='og:type')),
                ('meta1', models.CharField(blank=True, max_length=250, verbose_name='Свой html перед /head')),
                ('meta2', models.CharField(blank=True, max_length=250, verbose_name='Свой html после body')),
                ('meta3', models.CharField(blank=True, max_length=250, verbose_name='Свой html перед /body')),
            ],
            options={
                'verbose_name': 'Сео настройка страницы',
                'verbose_name_plural': 'Сео настройка страницы',
            },
        ),
    ]
