# Generated by Django 3.1.1 on 2020-10-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_intro_numbers_numberselements_pros_proselements_quote_requestsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intro',
            name='content',
            field=models.TextField(blank=True, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='intro',
            name='subtitle',
            field=models.CharField(blank=True, max_length=150, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='intro',
            name='title',
            field=models.CharField(blank=True, max_length=150, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='numbers',
            name='content',
            field=models.TextField(blank=True, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='numbers',
            name='subtitle',
            field=models.CharField(blank=True, max_length=150, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='numbers',
            name='title',
            field=models.CharField(blank=True, max_length=150, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='numberselements',
            name='number',
            field=models.CharField(max_length=150, verbose_name='Число'),
        ),
        migrations.AlterField(
            model_name='numberselements',
            name='text',
            field=models.CharField(max_length=150, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='pros',
            name='content',
            field=models.TextField(blank=True, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='pros',
            name='subtitle',
            field=models.CharField(blank=True, max_length=150, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='pros',
            name='title',
            field=models.CharField(blank=True, max_length=150, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='proselements',
            name='subtitle',
            field=models.CharField(blank=True, max_length=150, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='proselements',
            name='title',
            field=models.CharField(blank=True, max_length=150, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='author',
            field=models.CharField(blank=True, max_length=150, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='text',
            field=models.CharField(blank=True, max_length=150, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='requestsection',
            name='content',
            field=models.TextField(blank=True, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='requestsection',
            name='subtitle',
            field=models.CharField(blank=True, max_length=150, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='requestsection',
            name='title',
            field=models.CharField(blank=True, max_length=150, verbose_name='Заголовок'),
        ),
    ]
