# Generated by Django 3.1.1 on 2020-10-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201003_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='author',
            field=models.CharField(blank=True, max_length=150, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='text',
            field=models.CharField(blank=True, max_length=150, verbose_name='Текст'),
        ),
    ]
