# Generated by Django 3.1.1 on 2020-10-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20201003_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='text',
            field=models.CharField(blank=True, max_length=250, verbose_name='Текст'),
        ),
    ]
