# Generated by Django 3.1.1 on 2020-10-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20201003_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSeo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name='title')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='description')),
                ('og_title', models.CharField(blank=True, max_length=250, verbose_name='og_title')),
                ('og_description', models.CharField(blank=True, max_length=250, verbose_name='og_description')),
                ('og_url', models.CharField(blank=True, max_length=250, verbose_name='og_url')),
                ('og_image', models.CharField(blank=True, max_length=250, verbose_name='og_image')),
                ('og_type', models.CharField(blank=True, default='website', max_length=250, verbose_name='og_type')),
                ('meta1', models.CharField(blank=True, max_length=250, verbose_name='Свой html перед /head')),
                ('meta2', models.CharField(blank=True, max_length=250, verbose_name='Свой html после body')),
                ('meta3', models.CharField(blank=True, max_length=250, verbose_name='Свой html перед /body')),
            ],
            options={
                'verbose_name': 'Сео настройка страницы',
                'verbose_name_plural': 'Сео настройка страницы',
            },
        ),
    ]
