# Generated by Django 3.1.1 on 2020-10-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_pageseo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageseo',
            name='og_description',
            field=models.CharField(blank=True, max_length=250, verbose_name='og:description'),
        ),
        migrations.AlterField(
            model_name='pageseo',
            name='og_image',
            field=models.CharField(blank=True, max_length=250, verbose_name='og:image'),
        ),
        migrations.AlterField(
            model_name='pageseo',
            name='og_title',
            field=models.CharField(blank=True, max_length=250, verbose_name='og:title'),
        ),
        migrations.AlterField(
            model_name='pageseo',
            name='og_type',
            field=models.CharField(blank=True, default='website', max_length=250, verbose_name='og:type'),
        ),
        migrations.AlterField(
            model_name='pageseo',
            name='og_url',
            field=models.CharField(blank=True, max_length=250, verbose_name='og:url'),
        ),
    ]
