# Generated by Django 3.1.1 on 2020-10-03 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20201003_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='intro',
            name='content_en',
            field=models.TextField(blank=True, null=True, verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='intro',
            name='content_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='intro',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='intro',
            name='subtitle_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='intro',
            name='title_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='intro',
            name='title_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='numbers',
            name='content_en',
            field=models.TextField(blank=True, null=True, verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='numbers',
            name='content_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='numbers',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='numbers',
            name='subtitle_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='numbers',
            name='title_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='numbers',
            name='title_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='numberselements',
            name='number_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Число'),
        ),
        migrations.AddField(
            model_name='numberselements',
            name='number_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Число'),
        ),
        migrations.AddField(
            model_name='numberselements',
            name='text_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='numberselements',
            name='text_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='pros',
            name='content_en',
            field=models.TextField(blank=True, null=True, verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='pros',
            name='content_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='pros',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='pros',
            name='subtitle_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='pros',
            name='title_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='pros',
            name='title_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='proselements',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='proselements',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='proselements',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='proselements',
            name='subtitle_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='proselements',
            name='title_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='proselements',
            name='title_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='quote',
            name='author_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='quote',
            name='author_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='quote',
            name='text_en',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='quote',
            name='text_ru',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='requestsection',
            name='content_en',
            field=models.TextField(blank=True, null=True, verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='requestsection',
            name='content_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='requestsection',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='requestsection',
            name='subtitle_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='requestsection',
            name='title_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='requestsection',
            name='title_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок'),
        ),
    ]
