# Generated by Django 3.1.1 on 2020-10-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20201003_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Заголовок')),
                ('img_alt', models.CharField(blank=True, max_length=150, verbose_name='Alt тег изображения')),
                ('img', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Изображение раздела',
                'verbose_name_plural': 'Изображения раздела',
            },
        ),
        migrations.AddField(
            model_name='intro',
            name='img',
            field=models.ManyToManyField(to='home.SectionImages'),
        ),
        migrations.AddField(
            model_name='numbers',
            name='img',
            field=models.ManyToManyField(to='home.SectionImages'),
        ),
        migrations.AddField(
            model_name='pros',
            name='img',
            field=models.ManyToManyField(to='home.SectionImages'),
        ),
        migrations.AddField(
            model_name='quote',
            name='img',
            field=models.ManyToManyField(to='home.SectionImages'),
        ),
        migrations.AddField(
            model_name='requestsection',
            name='img',
            field=models.ManyToManyField(to='home.SectionImages'),
        ),
    ]
