# Generated by Django 3.1.1 on 2020-10-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20201005_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=150, verbose_name='Подзаголовок')),
                ('content', models.TextField(blank=True, verbose_name='Содержание')),
                ('img', models.ManyToManyField(blank=True, to='home.SectionImages', verbose_name='Изображения раздела')),
            ],
            options={
                'verbose_name': 'Раздел Услуги',
                'verbose_name_plural': 'Раздел Услуги',
            },
        ),
    ]
