# Generated by Django 3.1.1 on 2020-10-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20201005_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewsSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Заголовок')),
                ('title_ru', models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=150, verbose_name='Подзаголовок')),
                ('subtitle_ru', models.CharField(blank=True, max_length=150, null=True, verbose_name='Подзаголовок')),
                ('subtitle_en', models.CharField(blank=True, max_length=150, null=True, verbose_name='Подзаголовок')),
                ('content', models.TextField(blank=True, verbose_name='Содержание')),
                ('content_ru', models.TextField(blank=True, null=True, verbose_name='Содержание')),
                ('content_en', models.TextField(blank=True, null=True, verbose_name='Содержание')),
                ('img', models.ManyToManyField(blank=True, to='home.SectionImages', verbose_name='Изображения раздела')),
            ],
            options={
                'verbose_name': 'Раздел Услуги',
                'verbose_name_plural': 'Раздел Услуги',
            },
        ),
    ]
