# Generated by Django 3.1.1 on 2020-10-05 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_reviewssection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewssection',
            options={'verbose_name': 'Раздел Отзывы', 'verbose_name_plural': 'Раздел Отзывы'},
        ),
    ]
