# Generated by Django 3.1.1 on 2020-10-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='content',
            field=models.TextField(blank=True, verbose_name='Содержание'),
        ),
    ]
