# Generated by Django 3.1.1 on 2020-10-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20201003_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='img_alt',
            field=models.CharField(blank=True, max_length=150, verbose_name='Alt тег изображения'),
        ),
    ]
