# Generated by Django 3.1.1 on 2020-10-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=150, verbose_name='Подзаголовок')),
                ('content', models.TextField(blank=True, verbose_name='Контент')),
            ],
            options={
                'verbose_name': 'Страница портфолио',
                'verbose_name_plural': 'Страница портфолио',
            },
        ),
        migrations.AddField(
            model_name='portfolio',
            name='meta1',
            field=models.CharField(blank=True, max_length=250, verbose_name='Свой html перед /head'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='meta2',
            field=models.CharField(blank=True, max_length=250, verbose_name='Свой html после body'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='meta3',
            field=models.CharField(blank=True, max_length=250, verbose_name='Свой html перед /body'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='og_description',
            field=models.CharField(blank=True, max_length=250, verbose_name='og:description'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='og_image',
            field=models.CharField(blank=True, max_length=250, verbose_name='og:image'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='og_title',
            field=models.CharField(blank=True, max_length=250, verbose_name='og:title'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='og_type',
            field=models.CharField(blank=True, default='website', max_length=250, verbose_name='og:type'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='og_url',
            field=models.CharField(blank=True, max_length=250, verbose_name='og:url'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='page_description',
            field=models.CharField(blank=True, max_length=250, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='page_title',
            field=models.CharField(blank=True, max_length=250, verbose_name='title'),
        ),
    ]
