# Generated by Django 3.1.1 on 2020-10-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20201003_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliopage',
            name='img',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
